# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!
target 'MVVMPattern' do
  # Comment the next line if you don't want to use dynamic frameworks
  # Pods for MVVMPattern
  pod 'Alamofire'
  pod 'SnapKit'
  pod 'RxSwift'
  pod 'RxCocoa'
end
